GET http://localhost:8000/api/tasks HTTP/1.1
Content-Type: 'application/json'

###
GET http://localhost:8000/api/tasks/2 HTTP/1.1
Content-Type: 'application/json'

###

POST http://localhost:8000/api/tasks HTTP/1.1
Content-Type: : 'application/json'
Accept: 'application/json'

{
    "task" : "Task Three",
    "description" : "This is task three",
    "date" : "2020-05-21",
    "reminder" : true
}
###

PUT http://localhost:8000/api/tasks/3 HTTP/1.1
Content-Type: : 'application/json'
Accept: 'application/json'

{
    "task" : "Task two",
    "description" : "change to task two"
}


###

DELETE http://localhost:8000/api/tasks/1 HTTP/1.1
Content-Type: 'application/json'
